### ISSUE TITLE
Help regarding registering on Beckn

### ISSUE THREAD

**Issue by yashb042** [Konnect-Agri/protocol-server-beckn#2]
Hello,

I have looked up everywhere to find the actual registry where we register on Beckn, if you could help me with that, it will be really great. 

TIA

**Comment by techsavvyash** [comment]
Hey @yashb042 ,
You can use [this](https://github.com/sanjay95/BECKN-Integration-to-Gateway/blob/main/README.md) guide to onboard yourself on the beckn registry.
Thanks

**Comment by yashb042** [comment]
@techsavvyash Thanks for replying, the registry link mentioned here, is it real prod link where we can launch our app?

<img width="1037" alt="Screenshot 2023-06-02 at 12 59 44 PM" src="https://github.com/Konnect-Agri/protocol-server-beckn/assets/67835516/74e462fb-9f24-4a40-999f-a01845ef758b">

I can see there are lots of users, who have registered, but none of them feels like a genuine user. 
For example, namma yatri should be available in the user list right

**Comment by techsavvyash** [comment]
This is a deployed registry you can use to register the BAPs and BPPs

**Comment by yashb042** [comment]
@techsavvyash Is there any way to contact you, I think I'm just thinking in the wrong direction.
My linkedin is - https://www.linkedin.com/in/yashbansal042/
8619218273

I will be highly grateful to you

**Comment by yashb042** [comment]
Then why is namma yatri, paytm not visible here??

I got this API - 

curl --location 'https://pilot-gateway-1.beckn.nsdl.co.in/lookup' \
--header 'Content-Type: application/json' \
--data '{
    "type":"BG"
   
}'

Which is atleast returning some of the  fine looking registries

**Comment by techsavvyash** [comment]
What is your exact question? I believe your questions will be better answered when asked on github.com/beckn. You can ask your questions on their community discord as well.

**Comment by yashb042** [comment]
@techsavvyash I have already tried on both platforms, the responses there are not very clear, and the community is not quite active.

**Comment by techsavvyash** [comment]
Hey @yashb042,
I don't think we can provide a better answer then the beckn core team folks. But yes providers like PayTM will be present on ONDC.

**Comment by yashb042** [comment]
Let me put it this way then, you are implementing your app(Konnect-agri) after registering on BOC registry (registry.becknprotocol.io). Will you be able to make this productionalised? As in connect with other real BPPs and BAPs.

If no, you will have to register with ONDC also right?
I know, I'm getting a bit confused, but your patience would be much appreciated!!

**Comment by techsavvyash** [comment]
Our use case is for mortgages and we plan to create a open network for mortgage based BAPs and BPPs and will probably go deploy our own registry. But in case we want to develop something for the e-commerce world and becknise it we might have to get onboarded to ONDC. The steps to onboard on ONDC can be found on their official website.

**Comment by yashb042** [comment]
Makes sense!!!
So for my mobility use case, since it comes under e-commerce, we need not deploy our own registries, but just register with ONDC, and everything shall work.
No need to deploy protocol-servers also??

**Comment by techsavvyash** [comment]
I cannot conclusively answer this since I don't know if mobility is handles by ONDC or they handle their use case separately. Though I know that a separate spec for mobility exists.

**Comment by yashb042** [comment]
Yes, thanks a lot @techsavvyash for the help. Closing the issue.
